#include "ui_sensorEditScreen.h"
#include "ui_widgets.h"
#include "ui_theme.h"
#include "ui_cfg.h"
#include "ui_i18n.h"
#include "ui_nav.h"
#include "ui.h"
#include <string.h>
#include <stdio.h>
lv_obj_t *ui_sensorEditScreen=NULL;
static void rebuild(void){lv_obj_t*o=ui_sensorEditScreen;ui_sensorEditScreen=NULL;ui_sensorEditScreen_screen_init();ui_nav_replace(ui_sensorEditScreen);lv_obj_delete_delayed(o,250);}
static void unit_cb(lv_event_t*e){const char*k=lv_event_get_user_data(e);if(!strcmp(k,"psi")||!strcmp(k,"bar"))ui_cfg_set_pressure_unit(k);else ui_cfg_set_flow_unit(k);rebuild();}
static void p_switch(lv_event_t*e){bool hi=(bool)(intptr_t)lv_event_get_user_data(e);ui_cfg_set_pressure_limit_enabled(hi,lv_obj_has_state(lv_event_get_target(e),LV_STATE_CHECKED));}
static void limit_edit(lv_event_t*e){ui_edit_begin((ui_edit_target_t)(intptr_t)lv_event_get_user_data(e));ui_open_keypad_cb(e);}
static void f_switch(lv_event_t*e){bool hi=(bool)(intptr_t)lv_event_get_user_data(e);ui_cfg_set_flow_alarm(hi,lv_obj_has_state(lv_event_get_target(e),LV_STATE_CHECKED),ui_cfg_flow_limit(hi));}
static void limit_step(lv_event_t*e){int c=(int)(intptr_t)lv_event_get_user_data(e);ui_edit_target_t t=(ui_edit_target_t)(c<0?-c:c);ui_edit_begin(t);float step=(t==UI_EDIT_FLOW_HIGH?5.f:1.f);ui_edit_set_new(ui_edit_new()+(c>0?step:-step));ui_edit_apply();rebuild();}
static lv_obj_t*seg(lv_obj_t*p,const char*t,bool on,const char*k){lv_obj_t*b=lv_button_create(p);lv_obj_set_flex_grow(b,1);lv_obj_set_height(b,30);ui_style_button(b,on?UI_C_OK_BG:UI_C_CARD_BG2);lv_obj_t*l=ui_label(b,t,UI_FONT_XS,on?UI_C_OK:UI_C_TEXT_2);lv_obj_center(l);lv_obj_add_event_cb(b,unit_cb,LV_EVENT_CLICKED,(void*)k);return b;}
static lv_obj_t*card(lv_obj_t*p,const char*t){lv_obj_t*c=ui_card(p);lv_obj_set_flex_grow(c,1);lv_obj_set_height(c,78);lv_obj_set_style_pad_all(c,8,0);lv_obj_set_flex_flow(c,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_row(c,4,0);ui_label(c,t,UI_FONT_XS,UI_C_TEXT_2);return c;}
static lv_obj_t* mini(lv_obj_t*p,const char*t,int code){lv_obj_t*b=lv_button_create(p);lv_obj_set_size(b,30,30);ui_style_button(b,UI_C_CARD_BG2);lv_obj_t*l=ui_label(b,t,UI_FONT_MD,UI_C_TEXT);lv_obj_center(l);lv_obj_add_event_cb(b,limit_step,LV_EVENT_CLICKED,(void*)(intptr_t)code);return b;}
static lv_obj_t* value_button(lv_obj_t*p,const char*txt,ui_edit_target_t target,uint32_t color){lv_obj_t*b=lv_button_create(p);lv_obj_set_flex_grow(b,1);lv_obj_set_height(b,30);ui_style_button(b,UI_C_CARD_BG2);lv_obj_t*l=ui_label(b,txt,UI_FONT_MD,color);lv_obj_center(l);lv_obj_add_event_cb(b,limit_edit,LV_EVENT_CLICKED,(void*)(intptr_t)target);return b;}
static void pressure_card(lv_obj_t*p,const char*t,bool hi){ui_edit_target_t target=hi?UI_EDIT_PRES_MAX:UI_EDIT_PRES_MIN;lv_obj_t*c=card(p,t);lv_obj_t*r=ui_box(c);lv_obj_set_size(r,LV_PCT(100),45);lv_obj_set_flex_flow(r,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(r,5,0);lv_obj_set_flex_align(r,LV_FLEX_ALIGN_SPACE_BETWEEN,LV_FLEX_ALIGN_CENTER,LV_FLEX_ALIGN_CENTER);lv_obj_t*s=lv_switch_create(r);lv_obj_set_size(s,38,20);if(ui_cfg_pressure_limit_enabled(hi))lv_obj_add_state(s,LV_STATE_CHECKED);lv_obj_add_event_cb(s,p_switch,LV_EVENT_VALUE_CHANGED,(void*)(intptr_t)hi);mini(r,"-",-target);char b[24];char n[16];ui_cfg_press_fmt(n,sizeof(n),ui_cfg_press_to_disp(hi?ui_cfg_pressure_max():ui_cfg_pressure_min()));snprintf(b,sizeof(b),"%s %s",n,ui_cfg_pressure_unit());value_button(r,b,target,UI_C_ALARM);mini(r,"+",target);}
static void flow_card(lv_obj_t*p,const char*t,bool hi){ui_edit_target_t target=hi?UI_EDIT_FLOW_HIGH:UI_EDIT_FLOW_DELTA;lv_obj_t*c=card(p,t);lv_obj_t*r=ui_box(c);lv_obj_set_size(r,LV_PCT(100),45);lv_obj_set_flex_flow(r,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(r,5,0);lv_obj_set_flex_align(r,LV_FLEX_ALIGN_SPACE_BETWEEN,LV_FLEX_ALIGN_CENTER,LV_FLEX_ALIGN_CENTER);lv_obj_t*s=lv_switch_create(r);lv_obj_set_size(s,38,20);if(ui_cfg_flow_limit_enabled(hi))lv_obj_add_state(s,LV_STATE_CHECKED);lv_obj_add_event_cb(s,f_switch,LV_EVENT_VALUE_CHANGED,(void*)(intptr_t)hi);mini(r,"-",-target);char b[28];snprintf(b,sizeof(b),"%.0f %s",(double)ui_cfg_flow_to_disp(ui_cfg_flow_limit(hi)),ui_cfg_flow_unit());value_button(r,b,target,UI_C_WARN);mini(r,"+",target);}void ui_sensorEditScreen_screen_init(void){ui_sensorEditScreen=ui_screen_base();lv_obj_set_flex_flow(ui_sensorEditScreen,LV_FLEX_FLOW_COLUMN);lv_obj_set_style_pad_all(ui_sensorEditScreen,8,0);lv_obj_set_style_pad_row(ui_sensorEditScreen,6,0);ui_nav_header(ui_sensorEditScreen,_t("Sensores"));lv_obj_t*u=ui_card(ui_sensorEditScreen);lv_obj_set_size(u,LV_PCT(100),52);lv_obj_set_style_pad_all(u,7,0);lv_obj_set_flex_flow(u,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(u,7,0);ui_label(u,_t("Unidades"),UI_FONT_MD,UI_C_TEXT);lv_obj_t*ur=ui_box(u);lv_obj_set_flex_grow(ur,1);lv_obj_set_height(ur,34);lv_obj_set_flex_flow(ur,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(ur,5,0);seg(ur,"psi",!strcmp(ui_cfg_pressure_unit(),"psi"),"psi");seg(ur,"bar",!strcmp(ui_cfg_pressure_unit(),"bar"),"bar");seg(ur,"L/min",!strcmp(ui_cfg_flow_unit(),"lpm"),"lpm");seg(ur,"SCCM",!strcmp(ui_cfg_flow_unit(),"sccm"),"sccm");lv_obj_t*p=ui_box(ui_sensorEditScreen);lv_obj_set_size(p,LV_PCT(100),78);lv_obj_set_flex_flow(p,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(p,6,0);pressure_card(p,_t("Presión baja"),false);pressure_card(p,_t("Presión alta"),true);lv_obj_t*f=ui_box(ui_sensorEditScreen);lv_obj_set_size(f,LV_PCT(100),78);lv_obj_set_flex_flow(f,LV_FLEX_FLOW_ROW);lv_obj_set_style_pad_column(f,6,0);flow_card(f,_t("Cambio abrupto de flujo"),false);flow_card(f,_t("Flujo alto sostenido"),true);}
void ui_sensorEditScreen_screen_destroy(void){if(ui_sensorEditScreen){lv_obj_del(ui_sensorEditScreen);ui_sensorEditScreen=NULL;}}